spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://my-local-mysql:3306/poetry?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
